#!/bin/bash
# ============================================================
# Setup script for public Marketplace listing
# Run each section manually — some steps require GCP Console
# ============================================================

PROJECT_ID="attendance-tracker-pub"
PROJECT_NAME="Attendance Tracker Public"
REGION="us-central1"
SERVICE_NAME="attendance-tracker-backend"
SA_NAME="attendance-tracker-sa"
SA_EMAIL="${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"

echo "=== Step 1: Create new GCP project ==="
echo "Run: gcloud projects create ${PROJECT_ID} --name=\"${PROJECT_NAME}\""
echo ""
echo "Then link a billing account in the console:"
echo "https://console.cloud.google.com/billing?project=${PROJECT_ID}"
echo ""
echo "Press Enter when done..."
read

echo "=== Step 2: Enable required APIs ==="
echo "Run:"
echo "gcloud services enable \\"
echo "  meet.googleapis.com \\"
echo "  calendar-json.googleapis.com \\"
echo "  sheets.googleapis.com \\"
echo "  drive.googleapis.com \\"
echo "  firestore.googleapis.com \\"
echo "  secretmanager.googleapis.com \\"
echo "  admin.googleapis.com \\"
echo "  appsmarket-component.googleapis.com \\"
echo "  cloudbuild.googleapis.com \\"
echo "  run.googleapis.com \\"
echo "  --project=${PROJECT_ID}"
echo ""
echo "Press Enter when done..."
read

echo "=== Step 3: Create Firestore database ==="
echo "Run: gcloud firestore databases create --location=${REGION} --project=${PROJECT_ID}"
echo ""
echo "Press Enter when done..."
read

echo "=== Step 4: Create service account ==="
echo "Run:"
echo "gcloud iam service-accounts create ${SA_NAME} \\"
echo "  --display-name=\"Attendance Tracker Service Account\" \\"
echo "  --project=${PROJECT_ID}"
echo ""
echo "Grant roles:"
echo "gcloud projects add-iam-policy-binding ${PROJECT_ID} \\"
echo "  --member=serviceAccount:${SA_EMAIL} \\"
echo "  --role=roles/secretmanager.secretAccessor"
echo ""
echo "gcloud projects add-iam-policy-binding ${PROJECT_ID} \\"
echo "  --member=serviceAccount:${SA_EMAIL} \\"
echo "  --role=roles/datastore.user"
echo ""
echo "Press Enter when done..."
read

echo "=== Step 5: Create service account key + store in Secret Manager ==="
echo "Run:"
echo "gcloud iam service-accounts keys create /tmp/sa-key.json \\"
echo "  --iam-account=${SA_EMAIL} --project=${PROJECT_ID}"
echo ""
echo "gcloud secrets create service-account-key \\"
echo "  --data-file=/tmp/sa-key.json --project=${PROJECT_ID}"
echo ""
echo "gcloud secrets add-iam-policy-binding service-account-key \\"
echo "  --member=serviceAccount:${SA_EMAIL} \\"
echo "  --role=roles/secretmanager.secretAccessor \\"
echo "  --project=${PROJECT_ID}"
echo ""
echo "rm /tmp/sa-key.json"
echo ""
echo "Press Enter when done..."
read

echo "=== Step 6: Create OAuth client (MUST be done in Console) ==="
echo "Go to: https://console.cloud.google.com/apis/credentials?project=${PROJECT_ID}"
echo ""
echo "1. Configure OAuth consent screen first:"
echo "   - App name: Attendance Tracker"
echo "   - Support email: your email"
echo "   - Authorized domains: attendancetracker.dev, meet.google.com"
echo "   - Privacy Policy: https://attendancetracker.dev/privacy.html"
echo "   - Terms: https://attendancetracker.dev/terms.html"
echo "   - Publishing status: In production"
echo "   - User type: External"
echo ""
echo "2. Create OAuth Client ID:"
echo "   - Type: Web application"
echo "   - Name: Attendance Tracker"
echo "   - Authorized JS origins: https://attendancetracker.dev, https://meet.google.com"
echo "   - Authorized redirect URIs: https://${SERVICE_NAME}-XXXXXXX.${REGION}.run.app/"
echo ""
echo "3. Copy the Client ID and Client Secret"
echo ""
echo "Press Enter when done..."
read

echo "=== Step 7: Store OAuth secret ==="
echo "Run (replace YOUR_SECRET with the OAuth client secret):"
echo "echo|set /p=\"YOUR_SECRET\" > %TEMP%\\secret.txt"
echo "gcloud secrets create oauth-client-secret \\"
echo "  --data-file=%TEMP%\\secret.txt --project=${PROJECT_ID}"
echo "del %TEMP%\\secret.txt"
echo ""
echo "gcloud secrets add-iam-policy-binding oauth-client-secret \\"
echo "  --member=serviceAccount:${SA_EMAIL} \\"
echo "  --role=roles/secretmanager.secretAccessor \\"
echo "  --project=${PROJECT_ID}"
echo ""
echo "Press Enter when done..."
read

echo "=== Step 8: Generate session secret ==="
echo "Run:"
echo "node -e \"console.log(require('crypto').randomBytes(32).toString('base64'))\""
echo ""
echo "Copy the output for the next step."
echo ""
echo "Press Enter when done..."
read

echo "=== Step 9: Deploy Cloud Run ==="
echo "Run from backend/ directory:"
echo "cd backend"
echo "gcloud run deploy ${SERVICE_NAME} \\"
echo "  --source=. \\"
echo "  --project=${PROJECT_ID} \\"
echo "  --region=${REGION} \\"
echo "  --set-env-vars \"\\"
echo "    GOOGLE_CLIENT_ID=YOUR_NEW_CLIENT_ID,\\"
echo "    OAUTH_CLIENT_SECRET_NAME=projects/PROJECT_NUMBER/secrets/oauth-client-secret,\\"
echo "    SECRET_NAME=projects/PROJECT_NUMBER/secrets/service-account-key,\\"
echo "    SESSION_SECRET=YOUR_SESSION_SECRET,\\"
echo "    ALLOWED_DOMAINS=*,\\"
echo "    ALLOWED_ORIGINS=https://attendancetracker.dev\\,https://derekgallardo01.github.io\""
echo ""
echo "Press Enter when done..."
read

echo "=== Step 10: Configure Marketplace SDK (Console) ==="
echo "Go to: https://console.cloud.google.com/apis/api/appsmarket-component.googleapis.com/googleapps_sdk?project=${PROJECT_ID}"
echo ""
echo "1. App Configuration: name, description, icons, URLs"
echo "2. App Visibility: PUBLIC"
echo "3. Check 'Unlisted' to start (uncheck when ready for search)"
echo "4. Save and Publish"
echo ""
echo "=== Step 11: Update frontend config ==="
echo "Update APP_CONFIG in index.html with new project number and client ID"
echo "Or create a separate index-public.html that points to the new backend"
echo ""
echo "=== DONE ==="
echo "Your public Marketplace listing is ready!"
